function Bk_sym = Bk(in1,in2,in3,Ts)
%Bk
%    Bk_sym = Bk(IN1,IN2,IN3,Ts)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    14-Jul-2025 09:48:09

phi = in1(7,:);
si = in1(9,:);
theta = in1(8,:);
t2 = cos(phi);
t3 = cos(si);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(si);
t7 = sin(theta);
t8 = tan(theta);
t9 = 1.0./t4;
Bk_sym = reshape([0.0,0.0,0.0,0.0,0.0,0.0,Ts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ts.*t5.*t8,Ts.*t2,Ts.*t5.*t9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ts.*t2.*t8,-Ts.*t5,Ts.*t2.*t9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ts.*t3.*t4,Ts.*t4.*t6,-Ts.*t7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-Ts.*(t2.*t6-t3.*t5.*t7),Ts.*(t2.*t3+t5.*t6.*t7),Ts.*t4.*t5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Ts.*(t5.*t6+t2.*t3.*t7),-Ts.*(t3.*t5-t2.*t6.*t7),Ts.*t2.*t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[15,6]);
end
